# You are given a 2D Numpy array representing exam scores of students in different subjects. The array has shape (5,3), where each row reprfesents a
  students and each column represents a subject (Maths, Sciencee, English).

  Scores = np.array([[ 85,90,78],
                     [92,88,95],
                     [76,95,85],
                     [90,85,92],
                     [88,76,89]])

Using Numpy , perform the following tasks:
1. calculate the mean score of each subject ( across all students).
2. find the median score of each student ( acrossall the students).
3. Extract the scores of the student with the highest total score ( sum of all subjects).
4. Find the minimum and maximum scores in each subjects.
5. Reshape the array to have shape (3,5) where each row represents a subject.
6. Sort the scores of each subject in ascending order.
Note : Provide the code to accomplish each task , and include comments to explain your thoughts process.

In [2]:
import numpy as np

In [3]:
scores = np.array([[ 85,90,78],
                   [92,88,95],
                   [76,95,85],
                   [90,85,92],
                   [88,76,89]])
scores

array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [5]:

np.mean(scores, axis = 1)

array([84.33333333, 91.66666667, 85.33333333, 89.        , 84.33333333])

In [7]:
np.median(scores , axis = 1)

array([85., 92., 85., 90., 88.])

In [26]:
i =np.sum(scores, axis = 1)
i

array([253, 275, 256, 267, 253])

In [27]:
# Max
np.max(i)

np.int64(275)

In [28]:
# Min
np.min(scores, axis = 1)


array([78, 88, 76, 85, 76])

In [29]:
# Ascending Order
np.sort(scores)

array([[78, 85, 90],
       [88, 92, 95],
       [76, 85, 95],
       [85, 90, 92],
       [76, 88, 89]])

Reshape The Size

In [30]:
# Reshape the Array
np.reshape(scores,(3,5))

array([[85, 90, 78, 92, 88],
       [95, 76, 95, 85, 90],
       [85, 92, 88, 76, 89]])

In [33]:
# Max and Min
index=np.argmax(i)
index

np.int64(1)

In [34]:
scores[index]

array([92, 88, 95])

In [37]:
# Descending Order
np.sort(scores,axis = 0)[:: -1]

array([[92, 95, 95],
       [90, 90, 92],
       [88, 88, 89],
       [85, 85, 85],
       [76, 76, 78]])