In [1]:
# Numpy installed globally from Command prompt (pip install numpy)
import numpy as np

In [2]:
# 1D Arrays
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
print(arr.dtype)

int64


In [5]:
arr2 = np.array([1, 2, 3, 4, 5], dtype=np.int64)

In [6]:
arr2

array([1, 2, 3, 4, 5])

In [7]:
Z=np.zeros(5)

In [8]:
Z


array([0., 0., 0., 0., 0.])

In [9]:
Z=np.ones(5)

In [10]:
Z

array([1., 1., 1., 1., 1.])

In [11]:
ar=np.arange(0,10,1)

In [12]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
## random rand function always takes values between 0 -1
ran=np.random.rand(5)

In [14]:
ran

array([0.82809851, 0.3584629 , 0.22264066, 0.65875039, 0.23426181])

In [15]:
ln = np.linspace(0,100,10)

In [16]:
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [17]:
# 2D Arrays
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [18]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
Z=np.zeros([5,5])
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
o1 = np.ones([5,5])
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# Identity Matrix
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
r1 = np.random.rand(9,4,)
r1

array([[5.18470030e-01, 6.99959330e-01, 1.11074152e-03, 5.22040323e-01],
       [9.40927867e-01, 9.39803274e-01, 9.36591842e-01, 2.97180140e-01],
       [1.95395705e-01, 4.51043322e-02, 6.63628068e-01, 9.43358322e-01],
       [1.95168833e-02, 3.86254705e-01, 5.52283556e-05, 3.53065561e-01],
       [7.32279748e-02, 2.56599202e-01, 1.19326236e-01, 6.60336804e-01],
       [5.31220309e-01, 8.05515017e-02, 9.25624752e-03, 9.96596275e-01],
       [5.02708162e-02, 8.95499930e-01, 1.15751038e-01, 2.03002868e-01],
       [6.60133619e-01, 2.79814913e-01, 7.66757667e-01, 6.23101692e-01],
       [9.31938151e-01, 5.17923183e-01, 7.24266495e-01, 6.03537293e-01]])

In [23]:
arr

array([1, 2, 3, 4, 5])

In [24]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
print(arr.size)

5


In [26]:
print(ar2.size)

9


In [27]:
print(arr.shape)

(5,)


In [28]:
print(ar2.shape)

(3, 3)


In [29]:
# Operations in Array
ar3 = np.copy(ar2)
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
ar3[2,2] = 10

In [31]:
ar3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [32]:
ar3[1,2] =12
ar3[0,1] =15
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [33]:
ar3 = np.sort(ar3)
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [34]:
ar3 = np.sort(ar3,axis = 0)
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [35]:
ar3.sum(axis = 0)

array([12, 16, 37])

In [36]:
ar3.sum(axis = 1)

array([14, 21, 30])

In [37]:
ar4 = np.random.rand(99)
ar4

array([0.57035653, 0.36390625, 0.77023432, 0.35159128, 0.95529223,
       0.68380199, 0.62961099, 0.28957593, 0.13635781, 0.14115034,
       0.37984158, 0.33860259, 0.99955751, 0.26607862, 0.03465047,
       0.12127391, 0.0059824 , 0.96915852, 0.09171421, 0.52598001,
       0.34992071, 0.46177957, 0.09977133, 0.87853964, 0.15892112,
       0.9118498 , 0.2208111 , 0.43129976, 0.54798543, 0.76849318,
       0.39400005, 0.40874308, 0.6419587 , 0.10525594, 0.64826988,
       0.9045556 , 0.68412097, 0.07182461, 0.09239081, 0.42018847,
       0.23389006, 0.10709307, 0.28853551, 0.13579547, 0.37632966,
       0.37470369, 0.61030271, 0.78143387, 0.68347812, 0.96087947,
       0.6245854 , 0.90161513, 0.13266035, 0.20669988, 0.18095412,
       0.56758408, 0.96862876, 0.87119626, 0.56551929, 0.71393284,
       0.17069444, 0.8565563 , 0.23492395, 0.93809378, 0.3771386 ,
       0.51038554, 0.11785418, 0.13963293, 0.56723368, 0.26026901,
       0.25244898, 0.04485297, 0.11018169, 0.18941091, 0.10101

In [38]:
x = np.random.rand(5,5)
x

array([[0.07557547, 0.59910493, 0.60485143, 0.42602085, 0.49102028],
       [0.98901257, 0.74465525, 0.20697373, 0.50517552, 0.4386641 ],
       [0.23878534, 0.86732746, 0.41045072, 0.73926702, 0.96948899],
       [0.06856777, 0.85950021, 0.06134434, 0.01570134, 0.08530448],
       [0.79201175, 0.91537688, 0.03905083, 0.41039907, 0.07963036]])

In [39]:
x = np.random.rand(5,5,5)
x

array([[[0.94869813, 0.69232508, 0.59542221, 0.44207634, 0.98000237],
        [0.03341954, 0.54625691, 0.21139982, 0.29551809, 0.94493811],
        [0.41872754, 0.78521523, 0.41287564, 0.59143419, 0.99738099],
        [0.09005495, 0.13952953, 0.44785718, 0.38254334, 0.82416175],
        [0.59098116, 0.95134672, 0.40104302, 0.59845437, 0.6758682 ]],

       [[0.35570907, 0.64098617, 0.66699607, 0.21143764, 0.47277821],
        [0.55350985, 0.736517  , 0.1171306 , 0.25479468, 0.4576611 ],
        [0.04959094, 0.03303545, 0.45514796, 0.44573972, 0.40486499],
        [0.93770839, 0.5690587 , 0.84784041, 0.5174236 , 0.05552797],
        [0.57329091, 0.3683293 , 0.23511011, 0.50940533, 0.0860404 ]],

       [[0.95450794, 0.70420058, 0.06878561, 0.97484697, 0.5135527 ],
        [0.92239152, 0.74123762, 0.06077381, 0.33146489, 0.38591088],
        [0.976993  , 0.58009459, 0.90326332, 0.80429024, 0.85490548],
        [0.84434911, 0.11873643, 0.05790731, 0.4696539 , 0.2577156 ],
        [0.84559

In [40]:
print(arr.size)

5


In [41]:
print(ar2.size)

9


In [42]:
print(ar.shape)

(10,)


In [43]:
print(ar2.shape)

(3, 3)


In [44]:
arr3 = np.copy(ar2)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr3[2,2] = 10
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [46]:
arr3[1,2] =12
arr3[2,1] = 15
arr3

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7, 15, 10]])

In [47]:
arr3 = np.sort(arr3)
arr3

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7, 10, 15]])

In [48]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.append(ar, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20])

In [50]:
ar = np.append(ar,20)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20])

In [51]:
ar = np.delete(ar, 6, axis = 0)
ar

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 20])

In [52]:
ar = np.insert(ar,6,6)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20])

In [53]:
#Concatention
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [55]:
ar4 = np.concatenate((ar2, ar3),axis = 0)
ar4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [56]:
ar5 = np.concatenate((ar2, ar3),axis = 1)
ar5

array([[ 1,  2,  3,  1,  3, 10],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7,  8, 15]])

In [57]:
# Using Split function
np.split(ar4,3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [ 1,  3, 10]]),
 array([[ 4,  5, 12],
        [ 7,  8, 15]])]

In [58]:
ar6 = np.split(ar4,3)
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [ 1,  3, 10]]),
 array([[ 4,  5, 12],
        [ 7,  8, 15]])]

In [59]:
# Scaler Expressions
# Addition
np.add(ar5,1)

array([[ 2,  3,  4,  2,  4, 11],
       [ 5,  6,  7,  5,  6, 13],
       [ 8,  9, 10,  8,  9, 16]])

In [60]:
# Subtraction
np.subtract(ar5,1)

array([[ 0,  1,  2,  0,  2,  9],
       [ 3,  4,  5,  3,  4, 11],
       [ 6,  7,  8,  6,  7, 14]])

In [61]:
# Multiplication
np.multiply(ar5,1)

array([[ 1,  2,  3,  1,  3, 10],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7,  8, 15]])

In [62]:
# Divide 
np.divide(ar5,1)

array([[ 1.,  2.,  3.,  1.,  3., 10.],
       [ 4.,  5.,  6.,  4.,  5., 12.],
       [ 7.,  8.,  9.,  7.,  8., 15.]])

In [63]:
# Vector Operations
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [ 1,  3, 10]]),
 array([[ 4,  5, 12],
        [ 7,  8, 15]])]

In [64]:
# Addition
ar7 = np.add(ar6[0],ar6[1])
ar7

array([[ 8, 10, 12],
       [ 5,  8, 16]])

In [65]:
# Subtraction
ar8 = np.subtract(ar6[0],ar6[1])
ar8

array([[-6, -6, -6],
       [ 3,  2, -4]])

In [66]:
# Multiplication
ar9 = np.multiply(ar6[0],ar6[1])
ar9

array([[ 7, 16, 27],
       [ 4, 15, 60]])

In [67]:
# Divide
ar10 = np.divide(ar6[0],ar6[1])
ar10

array([[0.14285714, 0.25      , 0.33333333],
       [4.        , 1.66666667, 0.6       ]])

In [68]:
np.ceil(ar9)

array([[ 7., 16., 27.],
       [ 4., 15., 60.]])

In [69]:
np.floor(ar9)

array([[ 7., 16., 27.],
       [ 4., 15., 60.]])

In [70]:
np.round(ar9)

array([[ 7, 16, 27],
       [ 4, 15, 60]])

# Statistics

In [71]:
np.mean(ar5)

np.float64(6.111111111111111)

In [72]:
np.mean(ar5,axis = 0)

array([ 4.        ,  5.        ,  6.        ,  4.        ,  5.33333333,
       12.33333333])

In [73]:
np.mean(ar5, axis = 1)

array([3.33333333, 6.        , 9.        ])

In [74]:
np.median(ar5, axis = 1)

array([2.5, 5. , 8. ])

In [75]:
np.min(ar5)

np.int64(1)

In [76]:
np.min(ar5, axis = 0)

array([ 1,  2,  3,  1,  3, 10])

In [77]:
np.max(ar5, axis = 0)

array([ 7,  8,  9,  7,  8, 15])

In [78]:
ar10 = np.array([2,5,3,8,0,4,1,6,9])
ar5

array([[ 1,  2,  3,  1,  3, 10],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7,  8, 15]])

In [79]:
ar10

array([2, 5, 3, 8, 0, 4, 1, 6, 9])

In [80]:
np.argmax(ar10)

np.int64(8)

In [81]:
np.argmin(ar10)

np.int64(4)

In [82]:
np.argsort(ar10)

array([4, 6, 0, 2, 5, 1, 7, 3, 8])

In [83]:
ar10

array([2, 5, 3, 8, 0, 4, 1, 6, 9])

In [84]:
np.sin(ar10)

array([ 0.90929743, -0.95892427,  0.14112001,  0.98935825,  0.        ,
       -0.7568025 ,  0.84147098, -0.2794155 ,  0.41211849])

In [85]:
np.log(ar10)

C:\Users\gagan\AppData\Local\Temp\ipykernel_6632\168028880.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(ar10)


array([0.69314718, 1.60943791, 1.09861229, 2.07944154,       -inf,
       1.38629436, 0.        , 1.79175947, 2.19722458])