In [2]:
# Numpy installed globally from Command prompt (pip install numpy)
import numpy as np

In [3]:
# 1D Arrays
arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
print(arr.dtype)

int64


In [6]:
arr2 = np.array([1, 2, 3, 4, 5], dtype=np.int64)

In [7]:
arr2

array([1, 2, 3, 4, 5])

In [8]:
Z=np.zeros(5)

In [9]:
Z


array([0., 0., 0., 0., 0.])

In [10]:
Z=np.ones(5)

In [11]:
Z

array([1., 1., 1., 1., 1.])

In [12]:
ar=np.arange(0,10,1)

In [13]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
## random rand function always takes values between 0 -1
ran=np.random.rand(5)

In [15]:
ran

array([0.95296685, 0.35696124, 0.23894813, 0.45981223, 0.91095166])

In [16]:
ln = np.linspace(0,100,10)

In [17]:
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [18]:
# 2D Arrays
ar2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [19]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
Z=np.zeros([5,5])
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
o1 = np.ones([5,5])
o1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Identity Matrix
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
r1 = np.random.rand(9,4,)
r1

array([[0.77929469, 0.32148031, 0.00392272, 0.86172136],
       [0.84386208, 0.96036734, 0.50366532, 0.95628965],
       [0.0721157 , 0.40546184, 0.22593466, 0.36200107],
       [0.55567622, 0.80277993, 0.35042163, 0.85463506],
       [0.01470816, 0.05888661, 0.49030758, 0.55740536],
       [0.85809636, 0.16685936, 0.77645114, 0.13399865],
       [0.65784094, 0.71273972, 0.63028722, 0.80114353],
       [0.81080034, 0.825163  , 0.48540922, 0.63655726],
       [0.67035021, 0.05957507, 0.54342911, 0.48585214]])

In [24]:
arr

array([1, 2, 3, 4, 5])

In [25]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
print(arr.size)

5


In [27]:
print(ar2.size)

9


In [28]:
print(arr.shape)

(5,)


In [29]:
print(ar2.shape)

(3, 3)


In [30]:
# Operations in Array
ar3 = np.copy(ar2)
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
ar3[2,2] = 10

In [32]:
ar3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [33]:
ar3[1,2] =12
ar3[0,1] =15
ar3

array([[ 1, 15,  3],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [34]:
ar3 = np.sort(ar3)
ar3

array([[ 1,  3, 15],
       [ 4,  5, 12],
       [ 7,  8, 10]])

In [35]:
ar3 = np.sort(ar3,axis = 0)
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [36]:
ar3.sum(axis = 0)

array([12, 16, 37])

In [37]:
ar3.sum(axis = 1)

array([14, 21, 30])

In [38]:
ar4 = np.random.rand(99)
ar4

array([0.56048223, 0.12235869, 0.29524405, 0.66479709, 0.04950937,
       0.41039283, 0.46483273, 0.64500201, 0.59590445, 0.73068386,
       0.16768282, 0.01441076, 0.96656914, 0.9362982 , 0.42947634,
       0.89113398, 0.31742272, 0.06770056, 0.69941924, 0.69870547,
       0.90532926, 0.83889147, 0.62122177, 0.0805675 , 0.06784512,
       0.91037613, 0.58681381, 0.15197717, 0.21153147, 0.53852067,
       0.78376259, 0.33273701, 0.45836348, 0.71493502, 0.40134958,
       0.37688136, 0.14267031, 0.31577573, 0.19596272, 0.78400419,
       0.0551179 , 0.32536288, 0.64988101, 0.1890081 , 0.4733643 ,
       0.94473955, 0.22704807, 0.96597022, 0.90782289, 0.69103823,
       0.95860772, 0.83956465, 0.17754683, 0.19867257, 0.37042183,
       0.1115707 , 0.52770652, 0.21616731, 0.10559888, 0.14282051,
       0.72879728, 0.23809954, 0.52577536, 0.20084451, 0.93511611,
       0.52033361, 0.4394529 , 0.52476684, 0.06150722, 0.40015789,
       0.4838782 , 0.86937463, 0.91635062, 0.36286194, 0.39615

In [39]:
x = np.random.rand(5,5)
x

array([[0.41198512, 0.67567918, 0.21815632, 0.99145211, 0.97769652],
       [0.34671538, 0.91960098, 0.06301933, 0.96466329, 0.51516739],
       [0.41081375, 0.56898173, 0.58614911, 0.46127555, 0.54251721],
       [0.44627538, 0.33490073, 0.64321307, 0.12719505, 0.17465621],
       [0.31873561, 0.49658328, 0.6428368 , 0.46517576, 0.45545671]])

In [40]:
x = np.random.rand(5,5,5)
x

array([[[0.04411184, 0.36526546, 0.86206239, 0.74599964, 0.50798409],
        [0.92201953, 0.3204506 , 0.54357531, 0.14544996, 0.5054575 ],
        [0.86032036, 0.12386683, 0.2891101 , 0.5575588 , 0.64631642],
        [0.89029037, 0.87848443, 0.95266973, 0.53819143, 0.7926369 ],
        [0.14213453, 0.30423256, 0.34664526, 0.68030424, 0.84961744]],

       [[0.4366639 , 0.92206538, 0.89521782, 0.13222358, 0.06108128],
        [0.13719806, 0.22786539, 0.51289657, 0.98355211, 0.1522057 ],
        [0.01486898, 0.70737046, 0.23372572, 0.46931839, 0.34047434],
        [0.39072121, 0.52251334, 0.69496042, 0.31474018, 0.05249923],
        [0.09037249, 0.05167243, 0.84002045, 0.18501804, 0.40165229]],

       [[0.28057745, 0.5771532 , 0.34254967, 0.38421023, 0.26409135],
        [0.43248653, 0.15213681, 0.05369731, 0.80391895, 0.5968034 ],
        [0.61337614, 0.99017081, 0.74667936, 0.88117481, 0.43498114],
        [0.43443352, 0.56788445, 0.56879635, 0.24069943, 0.37193176],
        [0.74930

In [41]:
print(arr.size)

5


In [42]:
print(ar2.size)

9


In [43]:
print(ar.shape)

(10,)


In [44]:
print(ar2.shape)

(3, 3)


In [45]:
arr3 = np.copy(ar2)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr3[2,2] = 10
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [47]:
arr3[1,2] =12
arr3[2,1] = 15
arr3

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7, 15, 10]])

In [48]:
arr3 = np.sort(arr3)
arr3

array([[ 1,  2,  3],
       [ 4,  5, 12],
       [ 7, 10, 15]])

In [49]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.append(ar, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20])

In [51]:
ar = np.append(ar,20)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20])

In [52]:
ar = np.delete(ar, 6, axis = 0)
ar

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 20])

In [53]:
ar = np.insert(ar,6,6)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 20])

In [54]:
#Concatention
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
ar3

array([[ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [56]:
ar4 = np.concatenate((ar2, ar3),axis = 0)
ar4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  3, 10],
       [ 4,  5, 12],
       [ 7,  8, 15]])

In [57]:
ar5 = np.concatenate((ar2, ar3),axis = 1)
ar5

array([[ 1,  2,  3,  1,  3, 10],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7,  8, 15]])

In [58]:
# Using Split function
np.split(ar4,3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [ 1,  3, 10]]),
 array([[ 4,  5, 12],
        [ 7,  8, 15]])]

In [59]:
ar6 = np.split(ar4,3)
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [ 1,  3, 10]]),
 array([[ 4,  5, 12],
        [ 7,  8, 15]])]

In [60]:
# Scaler Expressions
# Addition
np.add(ar5,1)

array([[ 2,  3,  4,  2,  4, 11],
       [ 5,  6,  7,  5,  6, 13],
       [ 8,  9, 10,  8,  9, 16]])

In [61]:
# Subtraction
np.subtract(ar5,1)

array([[ 0,  1,  2,  0,  2,  9],
       [ 3,  4,  5,  3,  4, 11],
       [ 6,  7,  8,  6,  7, 14]])

In [62]:
# Multiplication
np.multiply(ar5,1)

array([[ 1,  2,  3,  1,  3, 10],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7,  8, 15]])

In [63]:
# Divide 
np.divide(ar5,1)

array([[ 1.,  2.,  3.,  1.,  3., 10.],
       [ 4.,  5.,  6.,  4.,  5., 12.],
       [ 7.,  8.,  9.,  7.,  8., 15.]])

Vector Operations

In [64]:
ar6

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [ 1,  3, 10]]),
 array([[ 4,  5, 12],
        [ 7,  8, 15]])]

In [65]:
# Addition
ar7 = np.add(ar6[0],ar6[1])
ar7

array([[ 8, 10, 12],
       [ 5,  8, 16]])

In [66]:
# Subtraction
ar8 = np.subtract(ar6[0],ar6[1])
ar8

array([[-6, -6, -6],
       [ 3,  2, -4]])

In [67]:
# Multiplication
ar9 = np.multiply(ar6[0],ar6[1])
ar9

array([[ 7, 16, 27],
       [ 4, 15, 60]])

In [68]:
# Divide
ar10 = np.divide(ar6[0],ar6[1])
ar10

array([[0.14285714, 0.25      , 0.33333333],
       [4.        , 1.66666667, 0.6       ]])

In [69]:
np.ceil(ar9)

array([[ 7., 16., 27.],
       [ 4., 15., 60.]])

In [70]:
np.floor(ar9)

array([[ 7., 16., 27.],
       [ 4., 15., 60.]])

In [71]:
np.round(ar9)

array([[ 7, 16, 27],
       [ 4, 15, 60]])

# Statistics

In [72]:
np.mean(ar5)

np.float64(6.111111111111111)

In [73]:
np.mean(ar5,axis = 0)

array([ 4.        ,  5.        ,  6.        ,  4.        ,  5.33333333,
       12.33333333])

In [74]:
np.mean(ar5, axis = 1)

array([3.33333333, 6.        , 9.        ])

In [75]:
np.median(ar5, axis = 1)

array([2.5, 5. , 8. ])

In [76]:
np.min(ar5)

np.int64(1)

In [77]:
np.min(ar5, axis = 0)

array([ 1,  2,  3,  1,  3, 10])

In [78]:
np.max(ar5, axis = 0)

array([ 7,  8,  9,  7,  8, 15])

In [79]:
ar10 = np.array([2,5,3,8,0,4,1,6,9])
ar5

array([[ 1,  2,  3,  1,  3, 10],
       [ 4,  5,  6,  4,  5, 12],
       [ 7,  8,  9,  7,  8, 15]])

In [80]:
ar10

array([2, 5, 3, 8, 0, 4, 1, 6, 9])

In [81]:
np.argmax(ar10)

np.int64(8)

In [82]:
np.argmin(ar10)

np.int64(4)

In [83]:
np.argsort(ar10)

array([4, 6, 0, 2, 5, 1, 7, 3, 8])

In [84]:
ar10

array([2, 5, 3, 8, 0, 4, 1, 6, 9])

In [85]:
np.sin(ar10)

array([ 0.90929743, -0.95892427,  0.14112001,  0.98935825,  0.        ,
       -0.7568025 ,  0.84147098, -0.2794155 ,  0.41211849])

In [86]:
np.log(ar10)

C:\Users\gagan\AppData\Local\Temp\ipykernel_8512\168028880.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(ar10)


array([0.69314718, 1.60943791, 1.09861229, 2.07944154,       -inf,
       1.38629436, 0.        , 1.79175947, 2.19722458])